name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      # * is a special character in YAML so we need to quote this string
      - "*"
  pull_request:
    branches:
      - main
  schedule:
    # * is a special character in YAML so we need to quote this string
    - cron: "0 0 * * SUN"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 - --version 1.2.0
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install project dependencies
      run: make install

    - name: Run tests
      run: make test
